var mongoose = require('mongoose');

var UnitSchema = new mongoose.Schema({
  nombre: String,
  altitud: String,
  departamento: String,
  municipio: String,
  ubicacion: String,
  areaTotal: String,
  areaCafe: String,
  lote: String,
  edadLote: String,
  variedad: {
	  	caturra: Boolean,
	  	bourbon: Boolean,
	  	catuai: Boolean,
	  	maragogype: Boolean,
	  	typica: Boolean,
	  	pacamara: Boolean,
	  	pacheComun: Boolean,
	  	pacheColis: Boolean,
	  	mundoNovo: Boolean,
	  },
  distanciamiento: String,
  sombra: Boolean,
  muestreo: Boolean,
  muestreoMes: String,
  fertilizaSuelo: Boolean,
  fertilizaSueloMes: String,
  fertilizaFollaje: Boolean,
  fertilizaFollajeMes: String,
  enmiendasSuelo: Boolean,
  enmiendasSueloMes: String,
  manejoTejido: Boolean,
  manejoTejidoMes: String,
  fungicidasRoya: Boolean,
  fungicidas: {
	  	contacto: Boolean,
	  	biologico: Boolean,
	  	sistemico: Boolean,
      bourbon: Boolean,
      catuai: Boolean
	  },
  fungicidasFechas: String,
  verificaAgua: Boolean,
  verificaAguaTipo: {
	  ph: Boolean,
	  dureza: Boolean,
  },
  rendimiento: String,
  floracionPrincipal: String,
  inicioCosecha:Date,
  finalCosecha:Date, 
  epocalluviosa:Date,
  FinEpocalluviosa:Date,
  recomendaciontecnica: String,
  nitrogeno : Boolean,
  nitrorealiza: String,
  sacos: String,
  realizapoda: Boolean,
  realizamonth: String,
  quetipo: String,
  enfermedades: Boolean,
  cyprosol: Boolean,
  cyprosoldate: String,
  atemi: Boolean,
  atemidate: String,
  esfera: Boolean,
  esferadate: String,
  opera: Boolean,
  operadate: String,
  opus: Boolean,
  opusdate: String,
  soprano: Boolean,
  sopranodate: String,
  hexalon: Boolean,
  hexalondate: String,
  propicon: Boolean,
  propicondate: String,  
  hexil: Boolean,
  hexildate: String,   
  otros: String,
  otrosdate: String,
  fungicidasmonth: String,
  realizamanejoTejidoMes: String,
  produccionhectarea: String,
  tipoCafe: {
	  estrictamenteDuro: Boolean,
	  duro: Boolean,
	  semiduro: Boolean,
	  prime: Boolean,
	  extraprime: Boolean
  },
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
},
{
    timestamps: true
});

mongoose.model('Unit', UnitSchema);